require("mini.comment").setup()
require("mini.cursorword").setup()
require("mini.fuzzy").setup()
require("mini.statusline").setup()
require("mini.starter").setup()
require("mini.surround").setup()
require("mini.tabline").setup()
